CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [EMAIL] NCHAR(100) NOT NULL, 
    [PASSWORD] NCHAR(100) NOT NULL, 
    [DATE_REGISTER] DATE NULL, 
    [DATE_LAST_LOGIN] DATE NULL, 
    [PASSWORD_RECOVERY] NCHAR(50) NULL, 
    [DATE_RECOVERY] NCHAR(50) NULL
)
